import { fetchWeatherApi } from "openmeteo";

export type WeatherHourlyData = {
	hour: number;
	temperature: number;
	precipitationProbability: number;
};

//Function generated by OpenMeteo API
export const getWeather = async () => {
	const params = {
		latitude: 51.54499100807906,
		longitude: -0.0200125821426322,
		current: ["temperature_2m", "apparent_temperature", "weather_code"],
		hourly: ["temperature_2m", "apparent_temperature", "weather_code"],
		daily: "weather_code",
		timezone: "Europe/London",
		forecast_days: 1,
	};
	const url = "https://api.open-meteo.com/v1/forecast";
	const responses = await fetchWeatherApi(url, params);
	const response = responses[0];

	const range = (start: number, stop: number, step: number) =>
		Array.from({ length: (stop - start) / step }, (_, i) => start + i * step);

	// Attributes for timezone and location
	const utcOffsetSeconds = response?.utcOffsetSeconds();
	const hourly = response?.hourly()!;

	console.log(hourly);

	// Note: The order of weather variables in the URL query and the indices below need to match!
	const weatherData = {
		hourly: {
			time: range(
				Number(hourly.time()),
				Number(hourly.timeEnd()),
				hourly.interval(),
			).map((t) => new Date((t + (utcOffsetSeconds ?? 0)) * 1000)),
			apparentTemperature: hourly.variables(0)?.valuesArray(),
			precipitationProbability: hourly.variables(1)?.valuesArray(),
			precipitation: hourly.variables(2)?.valuesArray(),
		},
	};

	console.log(weatherData);

	const now: Date = new Date();
	const currentHour: number = now.getHours();

	const hours = [
		currentHour,
		(currentHour + 2) % 24,
		(currentHour + 4) % 24,
		(currentHour + 8) % 24,
	];

	const weatherDataByHour: WeatherHourlyData[] = hours.map((hour) => ({
		hour: hour,
		temperature: weatherData.hourly.apparentTemperature[hour],
		precipitationProbability: weatherData.hourly.precipitationProbability[hour],
	}));

	console.log(weatherDataByHour);
	return weatherDataByHour;
};

export const getWeatherPanelData = async () => {
	return await getWeather();
};
